package com.heronix.talk.model.enums;

/**
 * Specific actions for audit log entries.
 */
public enum AuditAction {
    // Authentication
    LOGIN_SUCCESS,
    LOGIN_FAILED,
    LOGOUT,
    SESSION_EXPIRED,
    SESSION_TERMINATED,
    PASSWORD_CHANGED,
    PASSWORD_RESET,
    PASSWORD_RESET_REQUESTED,
    ACCOUNT_LOCKED,
    ACCOUNT_UNLOCKED,
    MFA_ENABLED,
    MFA_DISABLED,

    // User Management
    USER_CREATED,
    USER_UPDATED,
    USER_DELETED,
    USER_ACTIVATED,
    USER_DEACTIVATED,
    USER_ROLE_CHANGED,
    USER_PROFILE_UPDATED,

    // Role Management
    ROLE_CREATED,
    ROLE_UPDATED,
    ROLE_DELETED,
    PERMISSION_GRANTED,
    PERMISSION_REVOKED,

    // Channel Management
    CHANNEL_CREATED,
    CHANNEL_UPDATED,
    CHANNEL_DELETED,
    CHANNEL_ARCHIVED,
    MEMBER_ADDED,
    MEMBER_REMOVED,
    MEMBER_ROLE_CHANGED,

    // Message Operations
    MESSAGE_SENT,
    MESSAGE_EDITED,
    MESSAGE_DELETED,
    MESSAGE_PINNED,
    MESSAGE_UNPINNED,

    // System Configuration
    CONFIG_CREATED,
    CONFIG_UPDATED,
    CONFIG_DELETED,

    // Security Policy
    SECURITY_POLICY_CREATED,
    SECURITY_POLICY_UPDATED,
    SECURITY_POLICY_DELETED,
    SECURITY_POLICY_ACTIVATED,

    // Network Configuration
    NETWORK_CONFIG_CREATED,
    NETWORK_CONFIG_UPDATED,
    NETWORK_CONFIG_DELETED,

    // Emergency
    EMERGENCY_ALERT_SENT,
    EMERGENCY_ALERT_DISMISSED,
    LOCKDOWN_INITIATED,
    LOCKDOWN_LIFTED,

    // Data Operations
    DATA_EXPORTED,
    DATA_IMPORTED,
    BACKUP_CREATED,
    BACKUP_RESTORED,

    // API Access
    API_KEY_CREATED,
    API_KEY_REVOKED,
    API_ACCESS_DENIED,
    RATE_LIMIT_EXCEEDED,

    // General
    SYSTEM_STARTED,
    SYSTEM_STOPPED,
    MAINTENANCE_MODE_ENABLED,
    MAINTENANCE_MODE_DISABLED,
    SYNC_COMPLETED,
    SYNC_FAILED
}
